Latest_stable_version
ConstVol/imdb_helper pull request #1
Opened 2017-07-09 16:38 UTC by ConstVol

- sorting csv IMDB data by movie genre
- inline keyboard to choose movie genre
- rutracker API integration
  gem 'rutracker_api' out of date - need to change login link.
- cool oneliner functions

Probably oneliners are difficult to read but i wanted to try it.

2017-07-09 17:06 UTC, anatoliliotych requested changes

2017-07-09 17:06 UTC, anatoliliotych commented on bot.rb
> +  client = RutrackerApi.new('username', 'password')
where do you store username and password?

2017-07-09 17:06 UTC, anatoliliotych commented on bot.rb
> +  Telegram::Bot::Client.run('telegram_bot_token') do |bot|
what is the way to set token?

2017-07-09 17:06 UTC, anatoliliotych commented on bot.rb
> +class IMDB_Helper
how do you use this class? how to launch bot?

2017-07-09 17:06 UTC, anatoliliotych commented on bot.rb
> +  csv.each {|row| row.to_hash['genres'].split('|').each {|genre| genres[genre].push({row.to_hash['movie_title'] => row.to_hash['movie_imdb_link']})} if row.to_hash['imdb_score'].to_f > 7}
too long string! try to make code more readable

2017-07-09 17:26 UTC, ConstVol commented on bot.rb
> +class IMDB_Helper
I don't use it. I'll get rid of it.

2017-07-09 17:26 UTC, ConstVol commented on bot.rb
> +  client = RutrackerApi.new('username', 'password')
I'll create constants on top

2017-07-09 17:26 UTC, ConstVol commented on bot.rb
> +  csv.each {|row| row.to_hash['genres'].split('|').each {|genre| genres[genre].push({row.to_hash['movie_title'] => row.to_hash['movie_imdb_link']})} if row.to_hash['imdb_score'].to_f > 7}
will revert to a separete method

2017-07-09 17:26 UTC, ConstVol commented on bot.rb
> +  Telegram::Bot::Client.run('telegram_bot_token') do |bot|
I'll create constant on top

2017-07-09 17:27 UTC, anatoliliotych commented on bot.rb
> +  Telegram::Bot::Client.run('telegram_bot_token') do |bot|
use .env file for this with gem dotenv

2017-07-09 18:48 UTC, anatoliliotych requested changes

2017-07-09 18:48 UTC, anatoliliotych commented on bot.rb
> +USERNAME = ''
will this code work? or you will need to put creds here before launch? :)

use .env file with dotenv gem

2017-07-09 18:48 UTC, anatoliliotych commented on bot.rb
> +    movie['genres'].split('|').each do|genre|
style guide!

2017-07-09 18:48 UTC, anatoliliotych commented on bot.rb
> +      if movie['imdb_score'].to_f > 7
to float and checking with integer :)

2017-07-09 18:48 UTC, anatoliliotych commented on bot.rb
> +        torrent_id = client.search(term:movie.keys[0]).sort_by{|torrent| torrent[:size].split(" ")[0].to_f * size_to_kb[torrent[:size].split(" ")[1]]}.last[:torrent_id] unless search_result.is_a? Has
can you read this? try to make code readable

2017-07-09 18:48 UTC, anatoliliotych commented on bot.rb
> +
remove empty lines 
read style guide about this

2017-07-17 08:04 UTC, anatoliliotych requested changes

2017-07-17 08:04 UTC, anatoliliotych commented on bot.rb
> +        movie = genres[message.data].sample # get random movie by genre in ['title' => 'imdb_link'] form
If comments are obvious, I'd skip them.

2017-07-17 08:04 UTC, anatoliliotych commented on rutracker_api.rb
> +    @agent.get 'http://rutracker.org/forum/profile.php?mode=viewprofile&u=' + nick
URL to constant! you have lots of common in urls, try to prepare method which removes duplication

2017-07-17 08:04 UTC, anatoliliotych commented on rutracker_api.rb
> +
remove empty line

2017-07-17 08:04 UTC, anatoliliotych commented on rutracker_api.rb
> +      if row.css(".row1").text =~ /Не найдено/
make oneliner

2017-07-17 08:04 UTC, anatoliliotych commented on rutracker_handler.rb
> +      "https://rutracker.org/forum/viewtopic.php?t=#{torrent_id}"
url to constant

2017-07-17 08:04 UTC, anatoliliotych commented on sorter.rb
> +    @file_name = './data/movie_metadata.csv'
filename should be in constant

2017-07-17 08:04 UTC, anatoliliotych commented on sorter.rb
> +    @size_to_kb = {'KB' => 1, 'MB' => 1024, 'GB' => 1024*1024} # convert everything to KB in order compare sizes
use constant

2017-07-17 08:04 UTC, anatoliliotych commented on sorter.rb
> +    @size_to_kb = {'KB' => 1, 'MB' => 1024, 'GB' => 1024*1024} # convert everything to KB in order compare sizes
check style

2017-07-26 16:29 UTC, anatoliliotych reviewed
respond to code review!

2017-07-26 16:29 UTC, anatoliliotych commented on rutracker_api.rb
> +  SORT_OPTIONS = {asc: 1, desc: 2}
style guide!

2017-07-26 16:29 UTC, anatoliliotych commented on rutracker_api.rb
> +        return {error: 'Not found'}
style guide

2017-07-28 11:00 UTC, ConstVol commented on bot.rb
> +        movie = genres[message.data].sample # get random movie by genre in ['title' => 'imdb_link'] form
For some bodies it may not be so obvious

2017-07-28 11:03 UTC, ConstVol commented on rutracker_api.rb
> +      if row.css(".row1").text =~ /Не найдено/
It would be disrespectful to the creator of rutracker_api gem:)

2017-07-28 14:36 UTC, anatoliliotych requested changes

2017-07-28 14:36 UTC, anatoliliotych commented on bot.rb
> +        movie = genres[message.data].sample # get random movie by genre in ['title' => 'imdb_link'] form
try to write obvious and readable code :)

2017-07-28 14:36 UTC, anatoliliotych commented on rutracker_api.rb
> +      if row.css(".row1").text =~ /Не найдено/
please make : 
```
return {} if condition
```

2017-07-28 14:36 UTC, anatoliliotych commented on bot.rb
> +require 'dotenv/load'
add .env.example file

2017-07-28 14:36 UTC, anatoliliotych commented on rutracker_api.rb
> +    query = SEARCH_PAGE + '?'
is it worth to have this + ?

2017-07-28 14:37 UTC, anatoliliotych requested changes
Fix commit messages

2017-08-01 12:58 UTC, anatoliliotych approved these changes
LGTM

2017-11-16 12:05 UTC, merged